name: flowbots
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=2.114
  - blas-devel=3.9.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - ca-certificates=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cryptography=36.0.2
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - fonttools=4.32.0
  - freetype=2.10.4
  - idna=3.3
  - intel-openmp=2022.0.0
  - jbig=2.1
  - jpeg=9e
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.10
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libpng=1.6.37
  - libtiff=4.3.0
  - libuv=1.43.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-base=3.5.1
  - mkl=2022.0.0
  - mkl-devel=2022.0.0
  - mkl-include=2022.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - packaging=21.3
  - pandas=1.4.2
  - patsy=0.5.2
  - pillow=9.1.0
  - pip=22.0.4
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.5
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - pytz=2022.1
  - requests=2.27.1
  - scipy=1.8.0
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - setuptools=62.0.0
  - six=1.16.0
  - sqlite=3.37.1
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - tk=8.6.12
  - torchvision=0.12.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - attrs==21.4.0
    - babel==2.9.1
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - bleach==4.1.0
    - certifi==2021.10.8
    - colorama==0.4.4
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - imageio==2.15.0
    - ipykernel==6.12.1
    - ipython==8.2.0
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.1.1
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.2.1
    - jupyter-core==4.9.2
    - jupyter-server==1.16.0
    - jupyterlab==3.0.16
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.12.0
    - markupsafe==2.1.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.3.7
    - nbclient==0.5.13
    - nbconvert==6.4.5
    - nbformat==5.3.0
    - nest-asyncio==1.5.5
    - networkx==2.7.1
    - notebook==6.4.10
    - notebook-shim==0.1.0
    - numpy==1.19.5
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - prometheus-client==0.14.0
    - prompt-toolkit==3.0.29
    - psutil==5.9.0
    - pure-eval==0.2.2
    - pygments==2.11.2
    - pyparsing==3.0.7
    - pyrsistent==0.18.1
    - pywavelets==1.3.0
    - pywin32==303
    - pywinpty==2.0.5
    - pyzmq==22.3.0
    - scikit-image==0.18.2
    - send2trash==1.8.0
    - sniffio==1.2.0
    - soupsieve==2.3.2
    - stack-data==0.2.0
    - terminado==0.13.3
    - testpath==0.6.0
    - tifffile==2022.3.25
    - tornado==6.1
    - traitlets==5.1.1
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.2

